name: Problem report
description: Report an issue with a Kattis problem
title: "<problemname>: "
body:
  - type: dropdown
    id: category
    attributes:
      label: Labels
      multiple: true
      options:
        - weak data
        - incorrect data
        - incorrect bounds
        - time limit
        - clarity
        - statement
        - metadata
        - weak solutions
        - weak input validator
        - output validator crash
        - completely broken
        - other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What's wrong?
      description: >-
        Please don't include any secret data, judge solutions, or full solutions - describe without
        spoiling. If that's impossible, say so and we'll take details privately.
    validations:
      required: true
  - type: checkboxes
    id: fixer
    attributes:
      label: Fixing it
      options:
        - label: I'm willing to implement the fix myself
